cms/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from api.views import UsersView, UserView, UserLoginView, GuestViewSet, UserViewSet

urlpatterns = [

    url(r'^users/$', UsersView.as_view(), name='users'),
    url(r'^userOLD/$', UserView.as_view(), name='user'),
    url(r'^login/(?P<pk>\d+)/$', UserLoginView.as_view(), name='login'),
    url(r'^guests/$', GuestViewSet.as_view({'get': 'list', 'post':'create'}), name='guests'),
    url(r'^user/$', UserViewSet.as_view({'get': 'list', 'post': 'create'}), name='users'),

]

cms/cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cms_body.views import (AddDocument, AddUserView,
    # AuthorCreateView, AuthorDeleteView,
    # AuthorDetailView, AuthorUpdateView, AuthorView,
                            DocumentDeleteView, DocumentDetailView, DocumentListView,
                            EditionCreateView, EditionListView, EditionDeleteView,
                            EditionDetailView, EditionUpdateView,
                            GuestCreateView, GuestDetailView, GuestListView,
                            HostCreateView, HostDetailView, HostListView, IndexView,
                            MyView, UpdateDocumentView,
                            UserDetailView, UserLoginView, UserLogoutView, UserView, DocumentDetailPopView)


urlpatterns = [

    url(r'^api/', include('api.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^select2/', include('django_select2.urls')),


    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^index/', IndexView.as_view(), name='index'),
    url(r'^add_user/$', AddUserView.as_view(), name='add-user'),
    url(r'^user_login/$', UserLoginView.as_view(), name='user-login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),
    url(r'^users/$', UserView.as_view(), name='users'),
    url(r'^detail_user/(?P<pk>\d+)/$', UserDetailView.as_view(), name='user-detail'),
    url(r'^my/$', MyView.as_view(), name='my'),


    # url(r'^create_author/$', AuthorCreateView.as_view(), name='create-author'),
    # url(r'^update_author/(?P<pk>\d+)/$', AuthorUpdateView.as_view(), name='update-author'),
    # url(r'^delete_author/(?P<pk>\d+)/$', AuthorDeleteView.as_view(), name='delete-author'),
    # url(r'^detail_author/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    # url(r'^authors/$', AuthorView.as_view(), name='authors'),

    url(r'^detail_host/(?P<pk>\d+)/$', HostDetailView.as_view(), name='host-detail'),
    url(r'^hosts/$', HostListView.as_view(), name='hosts'),
    url(r'^create_host/$', HostCreateView.as_view(), name='create-host'),

    url(r'^detail_guest/(?P<pk>\d+)/$', GuestDetailView.as_view(), name='guest-detail'),
    url(r'^list_guest/$', GuestListView.as_view(), name='guests'),
    url(r'^create_guest/$', GuestCreateView.as_view(), name='create-guest'),

    url(r'^create_edition/$', EditionCreateView.as_view(), name='create-edition'),
    url(r'^update_edition/(?P<pk>\d+)/$', EditionUpdateView.as_view(), name='update-edition'),
    url(r'^delete_edition/(?P<pk>\d+)/$', EditionDeleteView.as_view(), name='delete-edition'),
    url(r'^detail_edition/(?P<pk>\d+)/$', EditionDetailView.as_view(), name='edition-detail'),
    url(r'^editions/$', EditionListView.as_view(), name='editions'),

    url(r'^update_document/(?P<pk>\d+)/$', UpdateDocumentView.as_view(), name='update-document'),
    url(r'^add_document/$', AddDocument.as_view(), name='add-document'),
    url(r'^detail_document/(?P<pk>\d+)/$', DocumentDetailView.as_view(), name='document-detail'),
    url(r'^detail_document_pop/(?P<pk>\d+)/$', DocumentDetailPopView.as_view(), name='document-detail-pop'),
    url(r'^documents/$', DocumentListView.as_view(), name='documents'),
    url(r'^delete_document/(?P<pk>\d+)/$', DocumentDeleteView.as_view(), name='delete-document'),


]

cms/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url
from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

cms/cms_body/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from tinymce import models as tinymce_models


# Create your models here.

OCENA = (
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
)


class User(AbstractUser):
    phone = models.CharField(max_length=15, null=False, verbose_name='Telefon')

    class Meta:
        verbose_name = "Użytkownik"
        verbose_name_plural = "Użytkownicy"


class Host(models.Model):
    name = models.CharField(max_length=40, null=False, verbose_name='Imię')
    surname = models.CharField(max_length=40, null=False, verbose_name='Nazwisko')
    phone = models.CharField(max_length=15, null=False, verbose_name='Telefon')

    def __str__(self):
        return "{} {}".format(self.name, self.surname)

    class Meta:
        verbose_name = "Prowadzący"
        verbose_name_plural = "Prowadzący"


class Guest(models.Model):
    name = models.CharField(max_length=40, verbose_name='Imię')
    surname = models.CharField(max_length=40, null=False, verbose_name='Nazwisko')
    phone = models.CharField(max_length=15, null=False, verbose_name='Telefon')
    alt_phone = models.CharField(max_length=128, null=True, blank=True, verbose_name='Telefon/Menadżer')
    notes = models.TextField(max_length=400, null=True, blank=True, verbose_name='Notatki')
    ocena = models.IntegerField(choices=OCENA, blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.name, self.surname)

    class Meta:
        verbose_name = "Gość"
        verbose_name_plural = "Goście"


class Edition(models.Model):
    date = models.DateField(auto_now_add=False, unique=True, verbose_name='Data')
    hosts = models.ManyToManyField(Host, related_name='editions', verbose_name='Prowadzący')
    editor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Wydawca')

    def __str__(self):
        return "Wydanie {}".format(self.date)

    class Meta:
        verbose_name = "Wydanie"
        verbose_name_plural = "Wydania"


class Document(models.Model):
    edition = models.ForeignKey(Edition, on_delete=models.CASCADE, null=True, related_name='documents', verbose_name='Wydanie')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='documents', verbose_name='Autor')
    published = models.BooleanField(default=False, verbose_name='Opublikować?')
    guests = models.ManyToManyField(Guest, blank=True, related_name='documents', verbose_name='Goście')
    notes = models.TextField(max_length=200, null=True, verbose_name='Info')
    topic = models.TextField(max_length=100, verbose_name='Tytuł')
    lead = models.TextField(max_length=400, null=True, verbose_name='Lead')
    content = tinymce_models.HTMLField(verbose_name='Treść', null=True)

    def __str__(self):
            return "{}".format(self.topic)

    class Meta:
        verbose_name = "Dokument"
        verbose_name_plural = "Dokumenty"

cms/cms_body/views.py
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from cms_body.forms import (AddUserForm, DocumentForm, DocumentSearchForm,
                            EditionSearchForm, GuestSearchForm, LoginForm)
from cms_body.models import Document, Edition, Guest, Host


User = get_user_model()

# INDEX


class IndexView(View):
    def get(self, request):
        ctx = {
            'editions': Edition.objects.all().order_by('-id')[0:10],
            'authors': User.objects.all().order_by('-id')[0:10],
            'documents': Document.objects.all().order_by('-id')[0:10],
            'guests': Guest.objects.all().order_by('-id')[0:10],
            'hosts': Host.objects.all().order_by('-id')[0:10],

        }
        if request.user.is_authenticated:
            return render(request, "index.html", ctx)
        else:
            return redirect('user-login')


# HOST


class HostDetailView(DetailView):
    model = Host


class HostListView(ListView):
    model = Host
    # template_name = 'cms_body/authors.html' # now - author_list.html


class HostCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'cms_body.add_document'
    model = Host
    fields = '__all__'
    success_url = reverse_lazy('hosts')


# GUEST


class GuestCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'cms_body.add_document'
    model = Guest
    fields = '__all__'
    success_url = reverse_lazy('guests')


class GuestListView(View):
    def get(self, request):
        ctx = {
            'guests': Guest.objects.all().order_by('-id')[0:10],
            'form': GuestSearchForm,
        }
        return render(request, 'guest_list.html', ctx)

    def post(self, request):
        form = GuestSearchForm(request.POST)
        if form.is_valid():
            guest_name = form.cleaned_data['name']
            guest_lastname = form.cleaned_data['lastname']
            all_guests_list = Guest.objects.all()
            for guest_name in guest_name.split():
                # guests_list1 = all_guests_list.filter(Q(name__icontains=guest_name) | Q(surname__icontains=guest_name)) # | Q(notes__icontains=guest_name))
                guests_list1 = all_guests_list.filter(name__icontains=guest_name)
            if guest_lastname:
                for guest_lastname in guest_lastname.split():
                    guests_list2 = all_guests_list.filter(surname__icontains=guest_lastname) # | Q(notes__icontains=guest_name))
                    guests_list = [obj for obj in guests_list1 if obj in guests_list2]
            else:
                guests_list = guests_list1
            #todo PAGINATION
            # print(guests_list)
            #
            # paginator = Paginator(guests_list, 10)
            # page = request.GET.get('page')
            # pag_list = paginator.get_page(page)

            ctx = {
                'guests': Guest.objects.all().order_by('-id')[0:10],
                'form': form,
                'guests_list': guests_list
                # 'pag_list': pag_list,
                # 'page': page,
                # 'paginator': paginator

            }
            return render(request, 'guest_list.html', ctx)

        ctx = {
            'guests': Guest.objects.all().order_by('-id')[0:20],
            'form': form,
        }
        return render(request, 'guest_list.html', ctx)


class GuestDetailView(DetailView):
    model = Guest


# EDITION


class DateInput(forms.DateInput):
    input_type = 'date'


MONTHS = {
    1: ('styczeń'), 2: ('luty'), 3: ('marzec'), 4: ('kwiecień'),
    5: ('maj'), 6: ('czerwiec'), 7: ('lipiec'), 8: ('sierpień'),
    9: ('wrzesień'), 10: ('październik'), 11: ('listopad'), 12: ('grudzień')
}


class EditionCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'cms_body.add_document'
    model = Edition
    fields = '__all__'
    success_url = reverse_lazy('editions')

    def get_form(self):
        # add date picker in forms
        from django.forms.widgets import SelectDateWidget
        import datetime
        year = datetime.date.today().year
        print(year)
        form = super(EditionCreateView, self).get_form()
        form.fields['date'].widget = SelectDateWidget(years=range(2017, year+1), months=MONTHS,  empty_label=("Rok", "Miesiąc", "Dzień"))
        return form


class EditionListView(View):
    def get(self, request):
        ctx = {
            'editions': Edition.objects.all().order_by('-id')[0:20],
            'form': EditionSearchForm,
            'button': "Szukaj",
        }
        return render(request, 'edition_list.html', ctx)

    def post(self, request):
        form = EditionSearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['data']
            try:
                edition = Edition.objects.get(date=data)
            except:
                edition = None
            ctx = {
                'form': form,
                'edition': edition,
                'editions': Edition.objects.all().order_by('-id')[0:20],
                'button': "Szukaj",

            }
            return render(request, 'edition_list.html', ctx)

        ctx = {
            'editions': Edition.objects.all().order_by('-id')[0:20],
            'form': form,
            'button': "Szukaj",
        }
        return render(request, 'edition_list.html', ctx)


class EditionUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'cms_body.add_document'
    model = Edition
    fields = '__all__'
    success_url = reverse_lazy('editions')

    def get_form(self):
        '''add date picker in forms'''
        from django.forms.widgets import SelectDateWidget
        form = super(EditionUpdateView, self).get_form()
        form.fields['date'].widget = SelectDateWidget()
        return form


class EditionDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'cms_body.add_document'
    model = Edition
    success_url = reverse_lazy('editions')


class EditionDetailView(DetailView):
    model = Edition


# DOCUMENT


class AddDocument(PermissionRequiredMixin, View):
    permission_required = 'cms_body.add_document'

    def get(self, request):
        ctx = {
            'form': DocumentForm,
            'head': "Dodaj dokumentację",
        }
        return render(request, "add_document.html", ctx)

    def post(self, request):
        form = DocumentForm(request.POST)
        if form.is_valid():
            current_user = request.user
            document = Document.objects.create(
                edition=form.cleaned_data['edition'],
                published=form.cleaned_data['published'],
                notes=form.cleaned_data['notes'],
                topic=form.cleaned_data['topic'],
                lead=form.cleaned_data['lead'],
                content=form.cleaned_data['content'],
                author=current_user)
            document.guests.set(form.cleaned_data['guests'])
            document.save()
            return HttpResponseRedirect(reverse('documents'))
        ctx = {
            'form': form,
            'head': "Dodaj dokumentację",
        }
        return render(request, "add_document.html", ctx)


class UpdateDocumentView(PermissionRequiredMixin, View):
    permission_required = 'cms_body.add_document'

    def get(self, request, pk):
        document = Document.objects.get(pk=pk)
        guests = Guest.objects.all().filter(documents=pk)
        form = DocumentForm(instance=document)
        ctx = {
            'form': form,
            'guests': guests,
            'head': "Zmień dokumentację",
        }
        return render(request, "add_document.html", ctx)

    def post(self, request, pk):
        document = Document.objects.get(pk=pk)
        form = DocumentForm(request.POST, instance=document)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('documents')
            )


class DocumentListView(View):
    def get(self, request):
        ctx = {
            'documents': Document.objects.all().filter(published=True).order_by('-id')[0:20],
            'form': DocumentSearchForm,
        }
        return render(request, 'document_list.html', ctx)

    def post(self, request):
        form = DocumentSearchForm(request.POST)
        if form.is_valid():
            slowo = form.cleaned_data['slowo']
            data = form.cleaned_data['data']
            if slowo:
                topic = Document.objects.filter(topic__icontains=slowo).order_by('-id').filter(published=True)
                lead = Document.objects.filter(lead__icontains=slowo).order_by('-id').filter(published=True)
                content = Document.objects.filter(content__icontains=slowo).order_by('-id').filter(published=True)

            else:
                topic = None
                lead = None
                content = None


            try:
                edition = Edition.objects.get(date=data)
            except:
                edition = None
            ctx = {

                'form': form,
                'edition': edition,
                'content': content,
                'lead': lead,
                'topic': topic,
                'documents': Document.objects.all().filter(published=True).order_by('-id')[0:20],
                'wyniki': None
            }
            return render(request, 'document_list.html', ctx)

        ctx = {

            'form': form,
        }
        return render(request, 'document_list.html', ctx)


class DocumentDetailView(DetailView):

cms/cms_body/templates/cms_body/author_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>USUNĄĆ ??? {{ object }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Usuń">
    </form>
     <button onclick="goBack()">Wróć</button>
    <p></p>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

cms/cms_body/templates/cms_body/author_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ object }}</h2>


    <p>
        Dokumentacje:<br>
        {% for object in author.documents.all|dictsortreversed:"id" %}
            {{ object.topic }} | {{ object.edition }}<br>
        {% endfor %}
    </p>



{% endblock %}

cms/cms_body/templates/cms_body/author_listOLD.html
{% extends 'base.html' %}

{% block content %}

    <h2>Autorzy:</h2>
    {% for object in object_list %}




                    <div class="container-list">
                    <a href="{% url 'host-detail' pk=object.id %}"> <span
                        class="glyphicon glyphicon-user"></span> {{ object.name }} {{ object.surname }} {{ object.phone }} </a>
                    </div>

            {% endfor %}


{% endblock %}

cms/cms_body/templates/cms_body/document_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <p>
    <h2>USUNĄĆ {{ object }} ???</h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Usuń!">
    </form>
    </p>
     <button onclick="goBack()">Wróć</button>
    <p></p>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>

{% endblock %}

cms/cms_body/templates/cms_body/document_detail.html
{% extends 'base.html' %}

{% block content %}
    <p></p>
    <button onclick="myFunction()">Wydrukuj stronę</button>
    <button onclick="goBack()">Wróć</button>

    <h1>{{ object }}</h1>
    <p> {{ object.edition }}<br>
        Autor: {{ object.author }}<br>
        Prowadzący:<br>
        {% for host in object.edition.hosts.all %}
            {{ host.name }} {{ host.surname }}<br>
        {% endfor %}
    </p>
    <p> Goście:<br>
        {% for guest in object.guests.all %}
            {{ guest.surname }} |  {{ guest.phone }}<bR>
        {% endfor %}
    </p>
    <p> Lead: <br>{{ object.lead }}</p>
    <p> Treść: <br>{% autoescape off %}{{ object.content }}{% endautoescape %}</p>


    <button onclick="myFunction()">Wydrukuj stronę</button>
    <button onclick="goBack()">Wróć</button>
    <p></p>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <script>
        function myFunction() {
            window.print();
        }
    </script>

{% endblock %}

cms/cms_body/templates/cms_body/document_detail_pop.html
{#{% extends 'base.html' %}#}
<html>
<body>

{#{% block content %}#}
    <p></p>
    <button onclick="myFunction()">Wydrukuj stronę</button>

    <h1>{{ object }}</h1>
    <p> {{ object.edition }}<br>
        Autor: {{ object.author }}<br>
        Prowadzący:<br>
        {% for host in object.edition.hosts.all %}
            {{ host.name }} {{ host.surname }}<br>
        {% endfor %}
    </p>
    <p> Goście:<br>
        {% for guest in object.guests.all %}
            {{ guest.surname }} |  {{ guest.phone }}<bR>
        {% endfor %}
    </p>
    <p> Lead: <br>{{ object.lead }}</p>
    <p> Treść: <br>{% autoescape off %}{{ object.content }}{% endautoescape %}</p>


    <button onclick="myFunction()">Wydrukuj stronę</button>

    <p></p>


    <script>
        function myFunction() {
            window.print();
        }
    </script>
</body>
</html>
{#{% endblock %}#}

cms/cms_body/templates/cms_body/edition_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
     <p>
    <h2>USUNĄĆ {{ object }} ???</h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Usuń!">
    </form>
    </p>
     <button onclick="goBack()">Wróć</button>
    <p></p>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>

{% endblock %}

cms/cms_body/templates/cms_body/edition_detail.html
{% extends 'base.html' %}

{% block content %}
    <p></p>
     <button onclick="goBack()">Wróć</button>
    <p></p>



    <h2>{{ object }}</h2>
    <h3>Wydawca: <a href="{% url 'user-detail' pk=object.editor.id %}"> <span class="glyphicon glyphicon-user"></span> {{ object.editor.last_name }}</h3> </a>
    <h3>Prowadzący:
        {% for object in edition.hosts.all %}
            <a href="{% url 'host-detail' pk=object.id %}"><span class="glyphicon glyphicon-user"></span> {{ object.surname }} </a>|
        {% endfor %}
    </h3>
    <h3>Dokumentacje: </h3>
    {% for object in edition.documents.all %}
        <h4> {{ forloop.counter }}. <a href="{% url 'document-detail' pk=object.id %}"><span
                class="glyphicon glyphicon-book"></span> {{ object.topic }} </a>
            <a href="{% url 'user-detail' pk=object.author.id %}"> <span class="glyphicon glyphicon-user"></span> {{ object.author.last_name }} </a> <br></h4>
        <h5>Goście:
            {% for object in object.guests.all %}
                <a href="{% url 'guest-detail' pk=object.id %}"><span class="glyphicon glyphicon-user"></span> {{ object.surname }} </a>|
            {% endfor %}
        </h5>
        <p> - - -</p>
    {% endfor %}

      <p></p>
     <button onclick="goBack()">Wróć</button>
    <p></p>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>

{% endblock %}

cms/cms_body/templates/cms_body/edition_form.html
{% extends 'base_form.html' %}
{% block beforeform %}
    <h1>Dodaj wydanie</h1>
{% endblock %}
{% block buttontext %}Dodaj{% endblock %}

cms/cms_body/templates/cms_body/guest_detail.html
{% extends 'base.html' %}

{% block content %}
    <p></p>
    <button onclick="goBack()">Wróć</button>

    <h1>{{ object }}</h1>

    <p> Telefon: {{ object.phone }}</p>
    <p> Telefon2: {{ object.alt_phone }}</p>
    <p> Notatki: {{ object.notes }}</p>
    <p> Ocena: {{ object.ocena }} </p>
    {# {{ object.get_ocena_display }}#}

    <p>
        Wizyty:<br>
        {% for object in guest.documents.all|dictsortreversed:"id" %}
            <a href="{% url 'document-detail' pk=object.id %}"><span
                    class="glyphicon glyphicon-book"></span> {{ object.topic }}</a> | <a href="{% url 'edition-detail' pk=object.edition.id %}"> {{ object.edition }} </a><br>
        {% endfor %}
    </p>


    <button onclick="goBack()">Wróć</button>
    <p></p>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

cms/cms_body/templates/cms_body/guest_form.html
{% extends 'base_form.html' %}

{% block beforeform %}
    <h1>Dodaj gościa:</h1>
{% endblock %}
{% block buttontext %}Dodaj {% endblock %}

cms/cms_body/templates/cms_body/host_form.html
{% extends 'base_form.html' %}

{% block beforeform %}
    <h1>Dodaj prowadzącego:</h1>
{% endblock %}
{% block buttontext %}Dodaj {% endblock %}

cms/cms_body/templates/cms_body/host_list.html
{% extends 'base.html' %}

{% block content %}

    <h2>Prowadzący:</h2>
    <ul>
        {% for object in object_list %}
            <li>
                <a href="{% url 'host-detail' pk=object.id %}"> <span
                        class="glyphicon glyphicon-user"></span> {{ object.name }} {{ object.surname }} </a>
            </li>
        {% endfor %}
    </ul>



{% endblock %}

cms/cms_body/templates/cms_body/user_list.html
{% extends 'base.html' %}

{% block content %}

     <h2>Autorzy:</h2>
    {% for object in object_list %}




                    <div class="container-list">
                    <a href="{% url 'host-detail' pk=object.id %}"> <span
                        class="glyphicon glyphicon-user"></span> {{ object.first_name }} {{ object.last_name }} {{ object.phone }} </a>
                    </div>

            {% endfor %}



{% endblock %}